version: '3.1'

services:
  db:
    image: mongo
    container_name: mongo
    # restart: always
    volumes:
      - .mongod.conf:/etc/mongod.conf
      # - ./logs:/var/log/mongod/
      # - ./db:/var/lib/mongod
      # - ./mongod.service:/lib/systemd/dydtem/mongod.service
    ports:
      - "27017:27017"

  app:
    image: akunduj/sre_node_app
    container_name: app
    # restart: always
    ports:
      - "80:3000"
    links:
      - db
    enviornment:
      - DB_HOST=mongodb://mongo:27017/posts